### ISSUE TITLE
eclypse Linux root password 

### ISSUE THREAD

**Issue by sazczmh** [Digilent/Eclypse-Z7#1]
Can you provide the Linux root password？Thanks very much!

**Comment by ionel-badisor** [comment]
petaliunx rootfs has user: root password: root
debian rootfs has user and password provided  in release section near download link.
https://github.com/Digilent/Eclypse-Z7/releases

**Comment by sazczmh** [comment]
> petaliunx rootfs has user: root password: root
> debian rootfs has user and password provided in release section near download link.
> https://github.com/Digilent/Eclypse-Z7/releases

Got it, thank you very much.
